steps:
# build the container image
- name: "gcr.io/cloud-builders/docker"
args: ["build", "-t", "gcr.io/jump-the-que/swychpayment", "."]
# push the container image to Container Registry

- name: "gcr.io/cloud-builders/docker"
args: ["push", "gcr.io/jump-the-que/swychpayment"]
# Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
args:
[
"beta",
"run",
"deploy",
"--allow-unauthenticated",
"jump-the-que",
"--image",
"gcr.io/jump-the-que/swychpayment",
"--region",
"us-central1",
"--platform",
"managed",
"--memory",
"128Mi"
]
images:
- gcr.io/jump-the-que/swychpayment